### ISSUE TITLE
Error during server join: java.lang.StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by HumanDuck23** [marvintheskid/mc-reverse-proxy#12]
Just cloned this repo and am trying to use the ProxyBootstrap class to make a proxy to join the eu.minemen.club minecraft server.
All I changed is the target default value in the ProxyBootstrap.java file.

Here is the log:
```
[12:36:29 INFO]: [proxy] Resolving address... (eu.minemen.club)
[12:36:29 INFO]: [proxy] Resolved server address: eu.minemen.club
[12:36:29 INFO]: [proxy] Listening on /[0:0:0:0:0:0:0:0]:25565
[12:36:36 INFO]: [proxy] Enabling encryption for /127.0.0.1:1157
[12:36:36 ERROR]: [proxy] An error happened during server join
java.lang.StringIndexOutOfBoundsException: begin 0, end 16, length 0
	at java.lang.String.checkBoundsBeginEnd(String.java:4601) ~[?:?]
	at java.lang.String.substring(String.java:2704) ~[?:?]
	at me.marvin.proxy.networking.pipeline.proxy.FrontendHandler.write(FrontendHandler.java:92) ~[api.jar:?]
```

Does this project actually handle MS auth for logging into online servers? Or do I need to use a different library for that?

**Comment by marvintheskid** [comment]
The project by itself only provides an API for authentication.

See the [SessionService](https://github.com/marvintheskid/mc-reverse-proxy/blob/master/api/src/main/java/me/marvin/proxy/utils/SessionService.java) interface for example.

If you want to join an online mode server, you have to set the [session variables](https://github.com/marvintheskid/mc-reverse-proxy/blob/master/api/src/main/java/me/marvin/proxy/Proxy.java#L95-L106) inside the Proxy class. You can fork the project and modify the [entry point](https://github.com/marvintheskid/mc-reverse-proxy/blob/master/standalone/src/main/java/me/marvin/proxy/InteractiveProxy.java), or you can create an addon for authentication.
